#!/bin/bash

# dockerhub
docker login -u ${DH_USER} -p ${DH_PASSWORD}
docker push ${REGISTRY_DH}/$DOCKERIMAGE:$DOCKERTAG

# quay.io
docker login -u ${CFD_QUAY_USER} -p ${CFD_QUAY_PASSWORD} quay.io
docker push ${REGISTRY_QUAY}/$DOCKERIMAGE:$DOCKERTAG
