#!/bin/bash

# dockerhub
docker login -u condaforgebot -p $DH_PASSWORD
docker push condaforge/$DOCKERIMAGE:$DOCKERTAG

# quay.io
docker login -u conda_forge_daemon -p ${CFD_QUAY_PASSWORD} quay.io
docker tag condaforge/$DOCKERIMAGE:$DOCKERTAG quay.io/condaforge/$DOCKERIMAGE:$DOCKERTAG
docker push quay.io/condaforge/$DOCKERIMAGE:$DOCKERTAG
