#!/bin/bash

docker login -u condaforgebot -p $DH_PASSWORD && \
  docker push condaforge/$DOCKERIMAGE:$DOCKERTAG

docker login -u conda_forge_daemon -p ${CFD_QUAY_PASSWORD} && \
  docker tag condaforge/$DOCKERIMAGE:$DOCKERTAG quay.io/condaforge/$DOCKERIMAGE:$DOCKERTAG && \
  docker push quay.io/condaforge/$DOCKERIMAGE:$DOCKERTAG
