#!/bin/bash -il

set -exo pipefail

export additional_channel=""

export miniforge_arch="$(uname -m)"
export miniforge_version="23.3.1-0"
export python_version="3.10"  # should match the one provided in miniforge
export condapkg="https://github.com/conda-forge/miniforge/releases/download/${miniforge_version}/Miniforge3-${miniforge_version}-Linux-${miniforge_arch}.sh"
if [ "$(uname -m)" = "x86_64" ]; then
   export conda_chksum="9be723d231609919fa3e3bb06f899a9a9c22e92e570bada8129a1bf50fee8d73"
elif [ "$(uname -m)" = "ppc64le" ]; then
   export conda_chksum="434b461d309110bfeb72198541a541985aa197e3b605de27978c15f31d1520ef"
elif [ "$(uname -m)" = "aarch64" ]; then
   export conda_chksum="b71277b8b40a6817d923fde0b858f56a4504f4e9b659d343dd8eae9d9473ab7f"
else
   exit 1
fi

# give sudo permission for conda user to run yum (user creation is postponed
# to the entrypoint, so we can create a user with the same id as the host)
echo 'conda ALL=NOPASSWD: /usr/bin/yum' >> /etc/sudoers
# give sudo permission to copy the cuda headers and libraries for cross compilation
echo 'conda ALL=NOPASSWD: /usr/bin/cp -r /opt/conda/targets/x86_64-linux /usr/local/cuda/targets/x86_64-linux' >> /etc/sudoers
echo 'conda ALL=NOPASSWD: /usr/bin/cp -r /opt/conda/targets/ppc64le-linux /usr/local/cuda/targets/ppc64le-linux' >> /etc/sudoers
echo 'conda ALL=NOPASSWD: /usr/bin/cp -r /opt/conda/targets/sbsa-linux /usr/local/cuda/targets/sbsa-linux' >> /etc/sudoers

# Install the latest Miniconda with Python 3 and update everything.
curl -s -L $condapkg > miniconda.sh
sha256sum miniconda.sh | grep $conda_chksum

bash miniconda.sh -b -p /opt/conda
rm -f miniconda.sh

# Work around TLS issues while updating conda's python and retrieving channel notices
export CONDA_NUMBER_CHANNEL_NOTICES="0"
touch /opt/conda/conda-meta/pinned
ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
source /opt/conda/etc/profile.d/conda.sh
conda activate
conda config --set show_channel_urls True
conda config --set channel_priority strict
conda config ${additional_channel} --add channels conda-forge
conda config --show-sources

# Update everything first
mamba update --yes --all

# Ensure conda build, deployment and docker tools are present
mamba install --yes --quiet \
    "python=$python_version" \
    git \
    patch \
    pip \
    conda-build \
    boa \
    anaconda-client \
    su-exec \
    tini

# Clean to reduce image size
conda clean -tipy

# Install docker tools
export CONDA_SUEXEC_INFO=( `conda list su-exec | grep su-exec` )
echo "su-exec ${CONDA_SUEXEC_INFO[1]}" >> /opt/conda/conda-meta/pinned
export CONDA_TINI_INFO=( `conda list tini | grep tini` )
echo "tini ${CONDA_TINI_INFO[1]}" >> /opt/conda/conda-meta/pinned

# Lucky group gets permission to write in the conda dir
groupadd -g 32766 lucky
chown -R $USER /opt/conda
chgrp -R lucky /opt/conda && chmod -R g=u /opt/conda
