#!/bin/bash -il

set -exo pipefail

export additional_channel="--add channels defaults"

export miniforge_version="4.8.5-2"
if [ "$(uname -m)" = "x86_64" ]; then
   export supkg="su-exec"
   export condapkg="https://github.com/conda-forge/miniforge/releases/download/${miniforge_version}/Miniforge3-${miniforge_version}-Linux-x86_64.sh"
   export conda_chksum="67e15be1628cfc191d95f84b7de4db82d11f32953245c913c7846a85fdbe68bc"
elif [ "$(uname -m)" = "ppc64le" ]; then
   export supkg="su-exec"
   export condapkg="https://github.com/conda-forge/miniforge/releases/download/${miniforge_version}/Miniforge3-${miniforge_version}-Linux-ppc64le.sh"
   export conda_chksum="13b535e744c879eb667272a4a5bc105c67e2ea69bc88b06acb5d2e80b1402caa"
elif [ "$(uname -m)" = "aarch64" ]; then
   export supkg="su-exec"
   export condapkg="https://github.com/conda-forge/miniforge/releases/download/${miniforge_version}/Miniforge3-${miniforge_version}-Linux-aarch64.sh"
   export conda_chksum="8352b5f24acf8409cf2717db68a744ef7ae5b3abf92bf901515e27be03461c55"
else
   exit 1
fi

# give sudo permission for conda user to run yum (user creation is postponed
# to the entrypoint, so we can create a user with the same id as the host)
echo 'conda ALL=NOPASSWD: /usr/bin/yum' >> /etc/sudoers

# Install the latest Miniconda with Python 3 and update everything.
curl -s -L $condapkg > miniconda.sh
sha256sum miniconda.sh | grep $conda_chksum

bash miniconda.sh -b -p /opt/conda
rm -f miniconda.sh
touch /opt/conda/conda-meta/pinned
ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
source /opt/conda/etc/profile.d/conda.sh
conda activate
conda config --set show_channel_urls True
conda config ${additional_channel} --add channels conda-forge
conda config --show-sources
conda update --all --yes
conda clean -tipy

# Install conda build and deployment tools.
conda install --yes --quiet \
    git patch \
    python=3.7 setuptools conda-build anaconda-client
conda clean -tipy

# Install docker tools
conda install --yes $supkg
export CONDA_SUEXEC_INFO=( `conda list $supkg | grep $supkg` )
echo "$supkg ${CONDA_SUEXEC_INFO[1]}" >> /opt/conda/conda-meta/pinned

conda install --yes tini
export CONDA_TINI_INFO=( `conda list tini | grep tini` )
echo "tini ${CONDA_TINI_INFO[1]}" >> /opt/conda/conda-meta/pinned
conda clean -tipy

# Lucky group gets permission to write in the conda dir
groupadd -g 32766 lucky
chown -R $USER /opt/conda
chgrp -R lucky /opt/conda && chmod -R g=u /opt/conda
